# Generated by Django 5.2.6 on 2026-02-10 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        ('sisalto', '0008_alter_epa_options_alter_specialty_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Emoji tai ikoni-koodi', max_length=50)),
                ('xp_reward', models.IntegerField(default=0)),
                ('condition_type', models.CharField(help_text='streak, mastery, questions, exam_pass, correct_streak, specialty_mastery, exam_score, time_based, specialty_coverage', max_length=50)),
                ('condition_value', models.IntegerField(help_text='Ehdon numeerinen arvo')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('questions_answered', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='progress_da_user_id_7360fb_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EPAProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_level_mastery', models.FloatField(default=0, help_text='0-100%')),
                ('a_level_questions_answered', models.IntegerField(default=0)),
                ('a_level_questions_correct', models.IntegerField(default=0)),
                ('b_level_mastery', models.FloatField(default=0, help_text='0-100%')),
                ('b_level_questions_answered', models.IntegerField(default=0)),
                ('b_level_questions_correct', models.IntegerField(default=0)),
                ('overall_mastery', models.FloatField(default=0, help_text='0-100%')),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('current_streak_days', models.IntegerField(default=0)),
                ('longest_streak_days', models.IntegerField(default=0)),
                ('epa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='sisalto.epa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epa_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'overall_mastery'], name='progress_ep_user_id_bc605e_idx')],
                'unique_together': {('user', 'epa')},
            },
        ),
        migrations.CreateModel(
            name='SpacedRepetitionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=0)),
                ('repetitions', models.IntegerField(default=0)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_cards', to='quiz.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sr_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'next_review'], name='progress_sp_user_id_86374b_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, help_text='Avointen kysymysten vastaukset')),
                ('calculation_answer', models.FloatField(blank=True, null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.FloatField(default=0, help_text='0-1 skaala')),
                ('confidence', models.IntegerField(blank=True, help_text='Itsearvioitu varmuus 1-5', null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.question')),
                ('selected_choices', models.ManyToManyField(blank=True, to='quiz.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['user', 'question'], name='progress_us_user_id_72f060_idx'), models.Index(fields=['user', 'attempted_at'], name='progress_us_user_id_ab4dd8_idx')],
            },
        ),
    ]
