# Generated by Django 5.2.6 on 2026-03-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_flaggedquestion_questionnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacedrepetitioncard',
            name='difficulty',
            field=models.FloatField(default=0, help_text='FSRS: vaikeusaste 1-10'),
        ),
        migrations.AddField(
            model_name='spacedrepetitioncard',
            name='elapsed_days',
            field=models.IntegerField(default=0, help_text='FSRS: päiviä edellisestä kertauksesta'),
        ),
        migrations.AddField(
            model_name='spacedrepetitioncard',
            name='fsrs_state',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Learning'), (2, 'Review'), (3, 'Relearning')], default=0, help_text='FSRS: kortin tila'),
        ),
        migrations.AddField(
            model_name='spacedrepetitioncard',
            name='lapses',
            field=models.IntegerField(default=0, help_text='FSRS: unohduskerrat'),
        ),
        migrations.AddField(
            model_name='spacedrepetitioncard',
            name='stability',
            field=models.FloatField(default=0, help_text='FSRS: muistin vahvuus (päiviä)'),
        ),
    ]
