# Generated by Django 5.2.6 on 2026-03-05 06:59

from django.db import migrations


def convert_sm2_to_fsrs(apps, schema_editor):
    """Convert existing SM-2 cards to FSRS state."""
    Card = apps.get_model('progress', 'SpacedRepetitionCard')
    for card in Card.objects.all():
        # Stability ≈ interval_days (how long memory lasts)
        card.stability = max(0.4, card.interval_days) if card.interval_days > 0 else 0.4
        # Difficulty: map ease_factor to FSRS difficulty (1-10)
        # ease_factor 1.3 → difficulty 9, 2.5 → 5, 3.5 → 2
        card.difficulty = max(1, min(10, 5 + (2.5 - card.ease_factor) * 3.33))
        # State: Review if mature, Learning if started, New if never reviewed
        if card.repetitions >= 2:
            card.fsrs_state = 2  # Review
        elif card.repetitions >= 1:
            card.fsrs_state = 1  # Learning
        else:
            card.fsrs_state = 0  # New
        card.lapses = 0
        card.elapsed_days = 0
        card.save()


def reverse_fsrs_to_sm2(apps, schema_editor):
    """No-op reverse — SM-2 fields are still intact."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_add_fsrs_fields'),
    ]

    operations = [
        migrations.RunPython(convert_sm2_to_fsrs, reverse_fsrs_to_sm2),
    ]
