# Generated by Django 5.2.6 on 2026-02-10 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sisalto', '0008_alter_epa_options_alter_specialty_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Monivalinta (1 oikea)'), ('multi_select', 'Monivalinta (useita oikeita)'), ('true_false', 'Oikein/Väärin'), ('calculation', 'Laskutehtävä'), ('open_ended', 'Avoin kysymys (AI-arviointi)'), ('matching', 'Yhdistä parit'), ('exam_essay', 'Tenttikysymys (AI-arviointi)')], max_length=20)),
                ('difficulty', models.IntegerField(choices=[(1, 'Helppo (A-taso perus)'), (2, 'Keskitaso (A-taso syvä)'), (3, 'Haastava (B-taso)'), (4, 'Vaikea (soveltava)'), (5, 'Erittäin vaikea (tenttitaso)')], default=2)),
                ('text', models.TextField(help_text='Kysymysteksti (Markdown)')),
                ('explanation', models.TextField(blank=True, help_text='Selitys oikeasta vastauksesta')),
                ('hint', models.TextField(blank=True, help_text='Vihje opiskelijalle')),
                ('calculation_answer', models.FloatField(blank=True, null=True)),
                ('calculation_tolerance', models.FloatField(blank=True, help_text='Sallittu poikkeama (%)', null=True)),
                ('calculation_unit', models.CharField(blank=True, help_text='Yksikkö (esim. mGy, mSv)', max_length=50)),
                ('model_answer', models.TextField(blank=True, help_text='Mallivastaus AI-arviointia varten')),
                ('scoring_rubric', models.TextField(blank=True, help_text='Pisteytysohje AI-arviointia varten')),
                ('max_points', models.IntegerField(default=1)),
                ('matching_pairs', models.JSONField(blank=True, help_text='[{"left": "termi", "right": "määritelmä"}]', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('epa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sisalto.epa')),
                ('learning_objectives', models.ManyToManyField(blank=True, related_name='questions', to='sisalto.learningobjective')),
            ],
            options={
                'ordering': ['epa', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, help_text='Miksi tämä on oikein/väärin')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('epa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_categories', to='sisalto.epa')),
            ],
            options={
                'verbose_name_plural': 'question categories',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.questioncategory'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['epa', 'question_type'], name='quiz_questi_epa_id_bc19e5_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='quiz_questi_difficu_fde0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='quiz_questi_is_acti_995386_idx'),
        ),
    ]
