# Generated by Django 5.2.6 on 2026-02-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
        ("sisalto", "0009_make_slugs_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="exam_question",
            field=models.ForeignKey(
                blank=True,
                help_text="Linkki tenttikysymykseen josta tämä monivalinta on johdettu",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quiz_questions",
                to="sisalto.examquestion",
            ),
        ),
    ]
