# Generated by Django 5.2.6 on 2026-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_add_exam_question_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Monivalinta (1 oikea)'), ('multi_select', 'Monivalinta (useita oikeita)'), ('true_false', 'Oikein/Väärin'), ('calculation', 'Laskutehtävä'), ('open_ended', 'Avoin kysymys (AI-arviointi)'), ('matching', 'Yhdistä parit'), ('cloze', 'Aukkotehtävä'), ('exam_essay', 'Tenttikysymys (AI-arviointi)')], max_length=20),
        ),
    ]
