# Generated by Django 5.2.6 on 2025-09-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sisalto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="epa",
            name="natiivikuvantaminen_content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
