# Generated by Django 5.2.6 on 2025-09-30 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sisalto", "0003_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="examquestion",
            options={"ordering": ["-year", "exam_date", "question_number"]},
        ),
        migrations.RemoveField(
            model_name="examquestion",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="examquestion",
            name="question",
        ),
        migrations.AddField(
            model_name="examquestion",
            name="exam_date",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="question_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="question_text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="semester",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="subject_area",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("user_answer", models.TextField()),
                ("gpt_evaluation", models.TextField(blank=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sisalto.examquestion",
                    ),
                ),
            ],
        ),
    ]
