# Generated by Django 5.2.6 on 2025-10-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sisalto", "0004_alter_examquestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="proficiency_level",
            field=models.CharField(
                choices=[
                    ("A1", "A1 - Aloittelija (Novice)"),
                    ("A2", "A2 - Edistynyt aloittelija (Advanced Beginner)"),
                    ("B1", "B1 - Pätevä (Competent)"),
                    ("B2", "B2 - Taitava (Proficient)"),
                    ("C1", "C1 - Asiantuntija (Expert)"),
                ],
                default="A1",
                max_length=2,
                verbose_name="Osaamisen taso",
            ),
        ),
    ]
