# Generated by Django 5.2.6 on 2025-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sisalto", "0005_section_proficiency_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="proficiency_level",
            field=models.CharField(
                choices=[
                    ("1", "1 — Aihe on uusi/tuntematon/vieras"),
                    ("2", "2 — Yleistason/teoreettinen ymmärrys"),
                    ("3", "3 — Ymmärtää ja osaa soveltaa käytännössä"),
                ],
                default="1",
                max_length=2,
                verbose_name="Osaamisen taso",
            ),
        ),
    ]
