# Generated by Django 5.2.6 on 2025-11-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sisalto", "0006_alter_section_proficiency_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
