# Generated by Django 5.2.6 on 2026-02-10 09:50

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug fields for existing EPA and Specialty records."""
    EPA = apps.get_model('sisalto', 'EPA')
    Specialty = apps.get_model('sisalto', 'Specialty')

    for specialty in Specialty.objects.all():
        base_slug = slugify(specialty.name, allow_unicode=True) or f'specialty-{specialty.pk}'
        slug = base_slug
        counter = 1
        while Specialty.objects.filter(slug=slug).exclude(pk=specialty.pk).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1
        specialty.slug = slug
        specialty.save(update_fields=['slug'])

    for epa in EPA.objects.all():
        base_slug = slugify(epa.title, allow_unicode=True) or f'epa-{epa.pk}'
        slug = base_slug
        counter = 1
        while EPA.objects.filter(slug=slug).exclude(pk=epa.pk).exists():
            slug = f'{base_slug}-{counter}'
            counter += 1
        epa.slug = slug
        epa.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('sisalto', '0007_alter_section_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epa',
            options={'ordering': ['specialty__order', 'order']},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['order'], 'verbose_name_plural': 'specialties'},
        ),
        migrations.AddField(
            model_name='epa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='epa',
            name='description',
            field=models.TextField(blank=True, help_text='Yleiskuvaus EPA-kortista'),
        ),
        migrations.AddField(
            model_name='epa',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='epa',
            name='references',
            field=models.TextField(blank=True, help_text='Viitekirjallisuus'),
        ),
        # Add slug fields WITHOUT unique constraint
        migrations.AddField(
            model_name='epa',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, default=''),
        ),
        migrations.AddField(
            model_name='specialty',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='specialty',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialty',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, default=''),
        ),
        # Populate slugs from existing titles/names
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Create LearningObjective model
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A', 'A-taso (perusosaaminen)'), ('B', 'B-taso (täydentävä osaaminen)')], max_length=1)),
                ('code', models.CharField(help_text='Esim. A1, A2, B1', max_length=10)),
                ('description', models.TextField()),
                ('theory_content', models.TextField(blank=True, help_text='Markdown-muotoinen teoriasisältö')),
                ('epa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='sisalto.epa')),
            ],
            options={
                'ordering': ['level', 'code'],
                'unique_together': {('epa', 'code')},
            },
        ),
    ]
