# Generated by Django 5.2.6 on 2026-02-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisalto', '0009_make_slugs_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='model_answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
