# Generated by Django 5.2.6 on 2026-02-19 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisalto', '0010_add_model_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='ai_evaluated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='ai_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='ai_strengths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='ai_suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='ai_weaknesses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='self_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
