# Generated by Django 5.2.6 on 2026-02-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisalto', '0011_examanswer_ai_evaluated_at_examanswer_ai_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(db_index=True, max_length=50)),
                ('tab_id', models.CharField(max_length=50)),
                ('slot_id', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='theory/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['modality', 'tab_id', 'order'],
                'unique_together': {('modality', 'tab_id', 'slot_id')},
            },
        ),
    ]
