# Generated by Django 5.2.6 on 2026-02-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisalto', '0012_theoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoryimage',
            name='display_size',
            field=models.CharField(choices=[('small', 'Pieni (40 %)'), ('medium', 'Normaali (65 %)'), ('large', 'Suuri (85 %)'), ('full', 'Täysleveys (100 %)')], default='medium', max_length=10),
        ),
    ]
