# Generated by Django 5.2.6 on 2026-02-10 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sisalto', '0008_alter_epa_options_alter_specialty_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('exam_type', models.CharField(choices=[('official_past', 'Virallinen vanha tentti'), ('practice', 'Harjoitustentti'), ('mock', 'Simuloitu tentti')], max_length=20)),
                ('year', models.IntegerField(blank=True, help_text='Tentin vuosi', null=True)),
                ('semester', models.CharField(blank=True, help_text='Esim. kevät, syksy', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('time_limit_minutes', models.IntegerField(default=180, help_text='Aikaraja minuuteissa')),
                ('passing_score_percent', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('epa_cards', models.ManyToManyField(blank=True, to='sisalto.epa')),
                ('specialties', models.ManyToManyField(blank=True, to='sisalto.specialty')),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Käynnissä'), ('submitted', 'Lähetetty arviointiin'), ('graded', 'Arvioitu')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('max_possible_score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.examtemplate')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamTemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('text', models.TextField(help_text='Kysymysteksti')),
                ('max_points', models.IntegerField(default=10)),
                ('model_answer', models.TextField(blank=True, help_text='Mallivastaus')),
                ('scoring_rubric', models.TextField(blank=True, help_text='Yksityiskohtainen pisteytysohje')),
                ('key_concepts', models.JSONField(blank=True, help_text='["käsite1", "käsite2"] - avainasiat jotka tulee mainita', null=True)),
                ('epa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sisalto.epa')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.examtemplate')),
                ('learning_objectives', models.ManyToManyField(blank=True, to='sisalto.learningobjective')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='ExamSessionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_strengths', models.JSONField(blank=True, null=True)),
                ('ai_weaknesses', models.JSONField(blank=True, null=True)),
                ('ai_suggestions', models.JSONField(blank=True, null=True)),
                ('ai_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('manual_score', models.FloatField(blank=True, null=True)),
                ('manual_feedback', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsession')),
                ('exam_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examtemplatequestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['user', 'status'], name='exams_exams_user_id_cfaeab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examtemplatequestion',
            unique_together={('exam', 'question_number')},
        ),
        migrations.AlterUniqueTogether(
            name='examsessionanswer',
            unique_together={('session', 'exam_question')},
        ),
    ]
